services:
  dashboard:
    image: grafana/grafana-oss:10.4.19
    container_name: grafana-server
    ports:
      - "8787:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  data_source:
    image: prom/prometheus:v2.52.0
    container_name: prometheus-server
    ports:
      - "8888:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped

volumes:
  grafana-data:
  prometheus-data:

